### ISSUE TITLE
Create a pkgdown site

### ISSUE THREAD

**Issue by andybeet** [andybeet/NEFSCspatial#3]
Create a pkgdown site on gh-pages branch
Use workflow to generate site

Should we have vignettes that visualize spatial data?
If so what is the best format for that?

**Comment by jmhatch** [comment]
@andybeet I tried to add a pkgdown site using `usethis::use_pkgdown_github_pages()` but ran into errors (I think b/c I'm not the repo owner). As a workaround, I added the `pkgdown` and `docs` folders to the repo. Could you turn on `gh-pages` using the `docs` folder?

**Comment by andybeet** [comment]
@jmhatch Site now visible from docs folder
