### ISSUE TITLE
create hexsticker

### ISSUE THREAD

**Issue by kimberly-bastille** [andybeet/NEFSCspatial#6]
build hex sticker for this package. What should it look like?

**Comment by jmhatch** [comment]
@kimberly-bastille Those icons are sick! I'm with @andybeet, I like the first one. Would it be possible to make the circle in the center of the map marker icon the NOAA logo? Just an idea, but if you don't like that or it's too much trouble forget about it.

**Comment by kimberly-bastille** [comment]
@jmhatch That is a great idea! Alicia said the same thing. I will make those edits and send up the changes soon.

**Comment by kimberly-bastille** [comment]
Here are the updated hexsticker options. I played around a bit with the colors to more closely match the NOAA logo colors but we can change any of that. 

![NEFSCspatial_hexsticker_v1](https://user-images.githubusercontent.com/39955661/172242058-544c4d56-d5a5-4ac0-80b9-9e0b287adf22.png)

![NEFSCspatial_hexsticker_v2](https://user-images.githubusercontent.com/39955661/172242047-27b615ab-0ad6-4de1-a913-46bfb24a00e5.png)

**Comment by andybeet** [comment]
@kimberly-bastille @jmhatch Looks great, still like the first one. The NOAA logo looks awesome too. If i was to make one comment, and it is minor, maybe nudge NEFSCspatial a little more toward the bottom of the hex to separate it from the blue box, or make all other content inside the hex a little smaller. Nice job!

**Comment by jmhatch** [comment]
These look so good @kimberly-bastille! I'm literally shook that you did most of this in ppt.
